#! /usr/bin/bash


#tbdelete table_name "name:Mohamed" "age:25"

table_name=$1
table_path=$DATA_PATH/$IN_USE_DB/$table_name.sql

counter=0

while read row
do
        sed -i "/$row/d" $table_path

        counter=$(( $counter+1 ))

done <<< $( when $table_name ${@:2} )

echo "$counter:Removed Successfully"

