#!/bin/bash

if [[ $# != 1 ]]; then
        echo "ERROR:Wrong Params"
	exit 1
fi

table_name=$1
table_path=$DATA_PATH/$IN_USE_DB
echo $table_path

if [[ -f "$table_path/$table_name.sql" && -f "$table_path/$table_name.schema" ]]; 
then
	read -p "Are you sure you want to drop $1 table?(Yy|Nn): " ans
	if [[ $ans =~ ^[Yy]$ ]]; then
		rm $table_path/"$table_name.sql" $table_path/"$table_name.schema"
		echo "$table_name Table Dropped "
        exit 0
	elif [[ $ans =~ ^[Nn]$  ]]; then
		echo "Aborted!"
        exit 3
	else
		echo "Aborted!"
        exit 3
	fi

else
	echo "Table Doesn't Exist" 2>&2
	exit 2
fi
